census_index:
    path:     /
    defaults: { _controller: MunicipalesBundle:Census:stepConditions }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

census_step_conditions:
    path:     /condiciones
    defaults: { _controller: MunicipalesBundle:Census:stepConditions }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
census_step1:
    path:     /paso1
    defaults: { _controller: MunicipalesBundle:Census:step1 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
 
census_step_verify:
    path:     /verificacion
    defaults: { _controller: MunicipalesBundle:Census:stepVerify }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
census_step2:
    path:     /localizacion
    defaults: { _controller: MunicipalesBundle:Census:step2 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
census_step3:
    path:     /registro
    defaults: { _controller: MunicipalesBundle:Census:step3 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
census_step4:
    path:     /alta-candidatura-paso-4
    defaults: { _controller: MunicipalesBundle:Census:step4 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
census_step5:
    path:     /final
    defaults: { _controller: MunicipalesBundle:Census:step5 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
 
# Ajax requests

ajax_get_municipalities_list:
    path:     /ajax/get-municipalities-list/{province_id}
    defaults: { _controller: MunicipalesBundle:Ajax:getMunicipalities }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

# http://municipales2015.listabierta.org./sms/inbound   
municipales_sms_inbound_callback:
    path:     /sms/inbound
    defaults: { _controller: MunicipalesBundle:SMSInbound:index }
    
# http://municipales2015.listabierta.org./sms/callback   
municipales_sms_callback:
    path:     /sms/callback
    defaults: { _controller: MunicipalesBundle:SMSInbound:callback }
    
login:
    pattern:   /login
    defaults:  { _controller: MunicipalesBundle:Security:login }
login_check:
    pattern:   /login_check
    
admin_logout:
    pattern:   /logout

recover_password:
    path:     /recover_password
    defaults: { _controller: MunicipalesBundle:Census:recoverPassword }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
recovery_token:
    path:     /recovery/{token}
    defaults: { _controller: MunicipalesBundle:Census:recoveryToken }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl