census_index:
    path:     /
    defaults: { _controller: MunicipalesBundle:Census:stepConditions }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

census_step1:
    path:     /condiciones
    defaults: { _controller: MunicipalesBundle:Census:stepConditions }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
census_step2:
    path:     /localizacion
    defaults: { _controller: MunicipalesBundle:Census:step2Location }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
census_step3:
    path:     /registro
    defaults: { _controller: MunicipalesBundle:Census:step3Register }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
census_step4:
    path:     /verificacion
    defaults: { _controller: MunicipalesBundle:Census:step4Verify }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
census_step5:
    path:     /final
    defaults: { _controller: MunicipalesBundle:Census:step5Finish }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

# http://municipales2015.listabierta.org./sms/inbound   
municipales_sms_inbound_callback:
    path:     /sms/inbound
    defaults: { _controller: MunicipalesBundle:SMSInbound:index }
    
# http://municipales2015.listabierta.org./sms/callback   
municipales_sms_callback:
    path:     /sms/callback
    defaults: { _controller: MunicipalesBundle:SMSInbound:callback }