Listabierta\Bundle\MunicipalesBundle\Entity\CensusUser:
    type: entity
    table: census_user
    repositoryClass: Listabierta\Bundle\MunicipalesBundle\Entity\CensusUserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        dni:
            type: string
            length: '15'
        email:
            type: string
            length: 255
            unique: TRUE
        isActive:
            type: boolean
            nullable: TRUE
        
        phone:
            type: string
            length: '20'
            
        token:
            type: string
            length: 255
            nullable: TRUE
            
        token:
            type: string
            length: 255
            nullable: TRUE
    
        provinceGeolocation:
            type: string
            length: 255
            nullable: TRUE 
            column: province_geolocation                      
 
        provinceLatitude:
            type: string
            length: 255
            nullable: TRUE 
            column: province_latitude
                  
        provinceLongitude:
            type: string
            length: 255
            nullable: TRUE 
            column: province_longitude    
       
        created_time:
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    
    actAs:
        Timestampable:
          created:
            name: created_time
          updated:
            disabled: true
    columns:
        created_time:
          type: timestamp
          notnull: true
        
    lifecycleCallbacks: {  }
